### ISSUE TITLE
How can I get the current value of an observable?

### ISSUE THREAD

**Issue by christianbundy** [mmckegg/mutant#27]
Instead of waiting for changes I'd prefer to get the current state of the observable. Is this possible to do with a `Value` observable? I've read through the code and can't seem to find a way to do it.

**Comment by mmckegg** [comment]
All observables in mutant are functions. To get their value, you just call them.

```js
var obs = Value()
obs.set('something')
obs() // => something
```

Whoops, I guess this is not in the docs.

**Comment by christianbundy** [comment]
That totally makes sense. I assumed that `obs()` was only for adding a listener.

I suppose something else that I didn't notice in the docs: does `obs(() => {})` return the value as well, or does that return a function to remove the listener? I've been spending a lot of time with [obv](https://github.com/dominictarr/obv) so I might be expecting some crossover that doesn't exist.

**Comment by mmckegg** [comment]
Yep, `obs(() => {})` returns a function that you can call to remove the listener.

There is some evolutionary tree stuff going on with all of these js observable modules 😆 

````
  observable
      |
    observ
    /    \
mutant    obv
