### ISSUE TITLE
no onListen opt in dict.js

### ISSUE THREAD

**Issue by mixmix** [mmckegg/mutant#4]
Hey @mmckegg , you proposed a nice onListen, onUnlisten approach to that patchbay network page the other day, but it didn't work.

Lookling closer, it appears dict doesnt respect onListen at all :) 

A rough read of the file (and comparing with `map.js`) I read 

```js
  // a line the deals with a listen function
  var binder = LazyWatcher(update, listen, unlisten)

  // a sad listen function
  function listen () {
    Object.keys(sources).forEach(function (key) {
      releases[key] = bind(sources[key])
    })
  }
  
  // I'm pretty sure that bind ain't gonna do anything, since: 
  function bind (key, valueOrObs) {
    return typeof valueOrObs === 'function' ? valueOrObs(updateKey.bind(this, key)) : null
  }
```

in `map.js`, I can see this for the associated listen : 

```js
  function listen () {
    if (typeof obs === 'function') {
      releases.push(obs(binder.onUpdate))
    }
    rebindAll()

    Array.from(itemInvalidators.values()).forEach(function (invalidators) {
      invalidators.forEach(function (invalidator) {
        invalidator.release = invalidator.observable(invalidate.bind(null, invalidator))
      })
    })

    if (opts && opts.onListen) {
      var release = opts.onListen()
      if (typeof release === 'function') {
        releases.push(release)
      }
    }
  }
```
Note the `opts.onListen`

I could get neck deep in this code and have a go at extending dict's functionality, but if this is an obvious fix to you, can you roll it out ? 

:cactus: :poodle:

**Comment by mmckegg** [comment]
Oh yeah, whoops. Added in v3.11.0!

I've been pretty slack about consistent options on all the different types. Have [added a test](https://github.com/mmckegg/mutant/blob/master/test/on-listen.js) that can be applied to any mutant "type" to test for `onListen` support. This could be a good pattern for checking interface consistency between the different types.

**Comment by mixmix** [comment]
awesome !
